-- 1. Display all bookings

SELECT * FROM Bookings;

-- 2. Total revenue generated

SELECT SUM(fare) AS Total_Revenue
FROM Bookings;

-- 3. Highest rated driver

SELECT *
FROM Drivers
ORDER BY rating DESC
LIMIT 1;

-- 4. Total rides by each driver

SELECT d.driver_name,
COUNT(b.booking_id) AS Total_Rides
FROM Drivers d
JOIN Bookings b
ON d.driver_id=b.driver_id
GROUP BY d.driver_name;

-- 5. Most active customer

SELECT c.customer_name,
COUNT(b.booking_id) AS Total_Bookings
FROM Customers c
JOIN Bookings b
ON c.customer_id=b.customer_id
GROUP BY c.customer_name
ORDER BY Total_Bookings DESC;

-- 6. Revenue generated by each driver

SELECT d.driver_name,
SUM(b.fare) AS Revenue
FROM Drivers d
JOIN Bookings b
ON d.driver_id=b.driver_id
GROUP BY d.driver_name;

-- 7. Average fare

SELECT AVG(fare) AS Average_Fare
FROM Bookings;

-- 8. City-wise customer count

SELECT city,
COUNT(*) AS Customers
FROM Customers
GROUP BY city;

-- 9. Cab usage report

SELECT c.cab_number,
COUNT(b.booking_id) AS Usage_Count
FROM Cabs c
JOIN Bookings b
ON c.cab_id=b.cab_id
GROUP BY c.cab_number;

-- 10. Booking details with customer and driver

SELECT cu.customer_name,
d.driver_name,
b.fare,
b.distance_km
FROM Bookings b
JOIN Customers cu
ON b.customer_id=cu.customer_id
JOIN Drivers d
ON b.driver_id=d.driver_id;
